const data = {
  
    products: [
      {
        //_id: '1',
        name: 'Hooked',
        slug: 'hooked',
        category: 'Business',
        image: 'https://blackwells.co.uk/jacket/l/9780241184837.jpg' , // 679px × 829px
        price: 120,
        countInStock: 10,
        Author: 'Nir Eyal',
        rating: 2.0,
        numReviews: 10,
        description: 'high quality pages',
      },
      {
        //_id: '2',
        name: 'This is Marketing',
        slug: 'this is Marketing',
        category: 'Business',
        image:'https://m.media-amazon.com/images/I/519BdwBLAAL._SY264_BO1,204,203,200_QL40_ML2_.jpg',
        price: 250,
        countInStock: 0,
        Author: 'Eric Rules',
        rating: 2.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        //_id: '3',
        name: 'The Lean Startup',
        slug: 'the Lean Startup',
        category: 'Business',
        image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1629999184i/10127019.jpg',
        price: 25,
        countInStock: 15,
        Author: 'David Heinemeier Hansson and Jason Fried',
        rating: 3.0,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        //_id: '4',
        name: 'Rework',
        slug: 'rework',
        category: 'Business',
        image: 'https://m.media-amazon.com/images/I/41woojfwaaL._SX329_BO1,204,203,200_.jpg',
        price: 65,
        countInStock: 5,
        brand: '',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
         //_id: '5',
        name: 'I will tell you to be rich',
        slug: 'i will tell you to be rich',
        category: 'Finance',
        image: 'https://m.media-amazon.com/images/I/51EGy99jixL._SY264_BO1,204,203,200_QL40_ML2_.jpg',
        price: 25,
        countInStock: 15,
        Author: 'Ramit Sethi',
        rating: 5.0,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        //_id: '6',
        name: 'Rich Dad Poor Dad',
        slug: 'rich Dad Poor Dad',
        category: 'Finance',
        image: 'https://m.media-amazon.com/images/I/51AHZGhzZEL.jpg',
        price: 25,
        countInStock: 15,
        Author: 'Robert T. Kiyoski',
        rating: 5.0,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        //_id: '7',
        name: 'Steve Jobs',
        slug: 'steve Jobs',
        category: 'Biography',
        image: 'https://bookoutlet.ca/_next/image?url=https%3A%2F%2Fimages.bookoutlet.com%2Fcovers%2Flarge%2Fisbn978198%2F9781982176860-l.jpg&w=640&q=75',
        price: 15,
        countInStock: 15,
        Author: 'Isaacson, Walter',
        rating: 5.0,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        //_id: '8',
        name: 'Leonardo Da Vinci',
        slug: 'leonardo Da Vinci',
        category: 'Biography',
        image: 'https://img.thriftbooks.com/api/images/i/m/EA9EB714DA73A3C3801AD22788F5C7E8CBB2B3D9.jpg',
        price: 25,
        countInStock: 15,
        Author: 'Isaacson, Walter',
        rating: 5.0,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        //_id: '9',
        name: 'The Art of Seduction',
        slug: 'the Art of Seduction',
        category: 'Health',
        image: 'https://img.fruugo.com/product/0/64/16158640_max.jpg',
        price: 45,
        countInStock: 15,
        Author: 'Robert Greene',
        rating: 5.0,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        //_id: '10',
        name: 'The Laws of Human Nature',
        slug: 'the Laws of Human Nature',
        category: 'health',
        image: 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9781/7812/9781781259191.jpg',
        price: 35,
        countInStock: 15,
        Author: 'Robert Greene',
        rating: 5.0,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        //_id: '11',
        name: 'Mastery',
        slug: 'mastery',
        category: 'Health',
        image: 'https://m.media-amazon.com/images/I/41WoD6VNvSL._SX349_BO1,204,203,200_.jpg',
        price: 25,
        countInStock: 15,
        Author: 'Robert Greene',
        rating: 5.0,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        //_id: '12',
        name: 'The Monk Who Sold His Ferrari',
        slug: 'the Monk Who Sold His Ferrari',
        category: 'Health',
        image: 'https://bookoutlet.ca/_next/image?url=https%3A%2F%2Fimages.bookoutlet.com%2Fcovers%2Flarge%2Fisbn978000%2F9780002008594-l.jpg&w=640&q=75',
        price: 25,
        countInStock: 0,
        Author: 'Robert Greene',
        rating: 5.0,
        numReviews: 14,
        description: 'high quality product',
      }
    ],
  };
  export default data;